### -*- coding: utf-8 -*-

import mechanize
import urllib,urllib2,re,cookielib
import base64
import os,sys,xbmc, xbmcgui, xbmcaddon, xbmcplugin
import xbmctools
import time,HTMLParser
from xml.dom.minidom import Document

def baslamak(threadName, delay):
    
    threadName=[]
    delay=[]
    html = xbmctools.sifre6()
    match = re.compile('Uyeliginiz: <strong>(.*?)</strong><br />').findall(html)
    for membership in match:
         membership=membership
    match2 = re.compile('Kullanici isminiz: <strong>(.*?)</strong><br />').findall(html)
    for uye in match2:
        uye=uye
    match3 = re.compile('Email adresiniz: <strong>(.*?)</strong><br />').findall(html)
    for email in match3:
        email=email
    match4 = re.compile('Giris yapmis oldugunuz sayi: <strong>(.*?)</strong>.*?<br />').findall(html)
    for girissayisi in match4:
        girissayisi=girissayisi
    match5 = re.compile('IP adresiniz: <strong>(.*?)</strong><br />').findall(html)
    for ipadd in match5:
        ipadd=ipadd
    match6 = re.compile('Uyeliginiz: <strong>(.*?)</strong>.*?</p>').findall(html)
    for tarih in match6:
        tarih=tarih

    TR = 'Turkish/'
    EN ='English/'
    GER = 'German/'
    FR = 'French/'
        
    test='c3RyaW5ncy5wbw=='
    htmlp = HTMLParser.HTMLParser()
    pfile=xbmc.translatePath('special://home/addons/plugin.video.magicTR/resources/language/'+TR)
    pfile1=xbmc.translatePath('special://home/addons/plugin.video.magicTR/resources/language/'+EN)
    pfile2=xbmc.translatePath('special://home/addons/plugin.video.magicTR/resources/language/'+GER)
    pfile3=xbmc.translatePath('special://home/addons/plugin.video.magicTR/resources/language/'+FR)
    filepath = base64.b64decode(test)
    f = open(pfile+filepath, "w")
    f1 = open(pfile1+filepath, "w")
    f2 = open(pfile2+filepath, "w")
    f3 = open(pfile3+filepath, "w")
    f.write('msgid ""\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350000"\n')
    f.write('msgid "[COLOR yellow][B]Uye Adiniz:[/B][/COLOR]"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350001"\n')
    f.write('msgid "'+'[COLOR beige][B]'+uye+'[/B][/COLOR]'+'"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350002"\n')
    f.write('msgid "[COLOR brown][B]Uyelik Turunuz:[/B][/COLOR]"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350003"\n')
    f.write('msgid "'+'[COLOR beige][B]'+membership+'[/B][/COLOR]'+'"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350004"\n')
    f.write('msgid "[COLOR green][B]IP Adresiniz:[/B][/COLOR]"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350005"\n')
    f.write('msgid "'+'[COLOR beige][B]'+ipadd+'[/B][/COLOR]'+'"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350006"\n')
    f.write('msgid "[COLOR red][B]Emailiniz:[/B][/COLOR]"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350007"\n')
    f.write('msgid "'+'[COLOR beige][B]'+email+'[/B][/COLOR]'+'"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350008"\n')
    f.write('msgid "[COLOR orange][B]Uyelik Bitis Tarihiniz:[/B][/COLOR]"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#350009"\n')
    f.write('msgid "'+'[COLOR beige][B]'+tarih+'[/B][/COLOR]'+'"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#3500010"\n')
    f.write('msgid "[COLOR purple][B]Sisteme Giris Sayiniz:[/B][/COLOR]"\n')
    f.write('msgstr ""\n\n')
    f.write('msgctxt "#3500011"\n')
    f.write('msgid "'+'[COLOR beige][B]'+girissayisi+'[/B][/COLOR]'+'"\n')
    f.write('msgstr ""\n')
    f.flush()
    f.close()
    
    f1.write('msgid ""\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350000"\n')
    f1.write('msgid "[COLOR yellow][B]Membership Name:[/B][/COLOR]"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350001"\n')
    f1.write('msgid "'+'[COLOR beige][B]'+uye+'[/B][/COLOR]'+'"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350002"\n')
    f1.write('msgid "[COLOR brown][B]Membership Type:[/B][/COLOR]"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350003"\n')
    f1.write('msgid "'+'[COLOR beige][B]'+membership+'[/B][/COLOR]'+'"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350004"\n')
    f1.write('msgid "[COLOR green][B]Your IP Address:[/B][/COLOR]"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350005"\n')
    f1.write('msgid "'+'[COLOR beige][B]'+ipadd+'[/B][/COLOR]'+'"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350006"\n')
    f1.write('msgid "[COLOR red][B]Your Email:[/B][/COLOR]"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350007"\n')
    f1.write('msgid "'+'[COLOR beige][B]'+email+'[/B][/COLOR]'+'"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350008"\n')
    f1.write('msgid "[COLOR orange][B]Membership End Date:[/B][/COLOR]"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#350009"\n')
    f1.write('msgid "'+'[COLOR beige][B]'+tarih+'[/B][/COLOR]'+'"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#3500010"\n')
    f1.write('msgid "[COLOR purple][B]Number of Enter :[/B][/COLOR]"\n')
    f1.write('msgstr ""\n\n')
    f1.write('msgctxt "#3500011"\n')
    f1.write('msgid "'+'[COLOR beige][B]'+girissayisi+'[/B][/COLOR]'+'"\n')
    f1.write('msgstr ""\n')
    f1.flush()
    f1.close()

    f2.write('msgid ""\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350000"\n')
    f2.write('msgid "[COLOR yellow][B]Mitgliedschaft Name:[/B][/COLOR]"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350001"\n')
    f2.write('msgid "'+'[COLOR beige][B]'+uye+'[/B][/COLOR]'+'"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350002"\n')
    f2.write('msgid "[COLOR brown][B]Typ der Mitgliedschaft:[/B][/COLOR]"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350003"\n')
    f2.write('msgid "'+'[COLOR beige][B]'+membership+'[/B][/COLOR]'+'"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350004"\n')
    f2.write('msgid "[COLOR green][B]Ihre IP Adresse:[/B][/COLOR]"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350005"\n')
    f2.write('msgid "'+'[COLOR beige][B]'+ipadd+'[/B][/COLOR]'+'"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350006"\n')
    f2.write('msgid "[COLOR red][B]Deine E-Mail:[/B][/COLOR]"\n')
    f2.write('msgstr ""\n')
    f2.write('msgctxt "#350007"\n')
    f2.write('msgid "'+'[COLOR beige][B]'+email+'[/B][/COLOR]'+'"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350008"\n')
    f2.write('msgid "[COLOR orange][B]Mitgliedschaft Enddatum:[/B][/COLOR]"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#350009"\n')
    f2.write('msgid "'+'[COLOR beige][B]'+tarih+'[/B][/COLOR]'+'"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#3500010"\n')
    f2.write('msgid "[COLOR purple][B]Anzahl Eingeben:[/B][/COLOR]"\n')
    f2.write('msgstr ""\n\n')
    f2.write('msgctxt "#3500011"\n')
    f2.write('msgid "'+'[COLOR beige][B]'+girissayisi+'[/B][/COLOR]'+'"\n')
    f2.write('msgstr ""\n')
    f2.flush()
    f2.close()

    f3.write('msgid ""\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350000"\n')
    f3.write('msgid "[COLOR yellow][B]Nom dadhésion:[/B][/COLOR]"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350001"\n')
    f3.write('msgid "'+'[COLOR beige][B]'+uye+'[/B][/COLOR]'+'"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350002"\n')
    f3.write('msgid "[COLOR brown][B]Type dadhésion:[/B][/COLOR]"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350003"\n')
    f3.write('msgid "'+'[COLOR beige][B]'+membership+'[/B][/COLOR]'+'"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350004"\n')
    f3.write('msgid "[COLOR green][B]Votre adresse IP:[/B][/COLOR]"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350005"\n')
    f3.write('msgid "'+'[COLOR beige][B]'+ipadd+'[/B][/COLOR]'+'"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350006"\n')
    f3.write('msgid "[COLOR red][B]Ton E-Mail:[/B][/COLOR]"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350007"\n')
    f3.write('msgid "'+'[COLOR beige][B]'+email+'[/B][/COLOR]'+'"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350008"\n')
    f3.write('msgid "[COLOR orange][B]Membre Date de fin:[/B][/COLOR]"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#350009"\n')
    f3.write('msgid "'+'[COLOR beige][B]'+tarih+'[/B][/COLOR]'+'"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#3500010"\n')
    f3.write('msgid "[COLOR purple][B]Nombre de Entrez:[/B][/COLOR]"\n')
    f3.write('msgstr ""\n\n')
    f3.write('msgctxt "#3500011"\n')
    f3.write('msgid "'+'[COLOR beige][B]'+girissayisi+'[/B][/COLOR]'+'"\n')
    f3.write('msgstr ""\n')
    f3.flush()
    f3.close()


def playlist3():
        rss='UnNzRmVlZHMueG1s'
        nos='ICA8c2V0IGlkPSIxIj4NCg0KICAgIDxmZWVkIHVwZGF0ZWludGVydmFsPSIzMCI+aHR0cHM6Ly9rb2RpdHIub3JnL3hibWN0ci9mZWVkLnhtbDwvZmVlZD4NCg0KICAgIDxmZWVkIHVwZGF0ZWludGVydmFsPSIzMCI+aHR0cHM6Ly9rb2RpdHIub3JnL3hibWN0ci92b2xrYW42NC54bWw8L2ZlZWQ+DQogICAgDQogICAgPGZlZWQgdXBkYXRlaW50ZXJ2YWw9IjMwIj5odHRwczovL2tvZGl0ci5vcmcveGJtY3RyL2JpbGdpbi54bWw8L2ZlZWQ+DQoNCiAgPC9zZXQ+'
        htmlp = HTMLParser.HTMLParser()
        pfile=xbmc.translatePath("special://home/userdata/")
        doc = Document()
        renk=doc.toprettyxml
        liste = doc.createElement("rssfeeds")
        doc.appendChild(liste)
        veri_ad = doc.createTextNode(base64.b64decode(nos))
        liste.appendChild(veri_ad)
        filepath = base64.b64decode(rss)
        f = open(pfile+filepath, "w")
        f.write(htmlp.unescape(renk(indent="")))
